# Generated by Django 5.0.3 on 2024-03-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exoticanimal',
            name='type_of_animal',
            field=models.CharField(max_length=50),
        ),
    ]
